---
backrest_version: "v1.12.0"
backrest_url: "https://github.com/garethgeorge/backrest/releases/download/{{ backrest_version }}/backrest_Linux_x86_64.tar.gz"
backrest_port: "9898"
host: "0.0.0.0"
backrest_user: "restic"
