[workstations]
nr200

[pvevmdeb]
#deb-podman2 ansible_host=192.168.6.210
#deb-virtio-test2 ansible_host=192.168.6.11
#deb-virtio-test3 ansible_host=192.168.6.12
deb-podman-test5 ansible_host=192.168.6.13

[pvevm]
#alma-test ansible_host=192.168.6.177
alma2 ansible_host=192.168.6.181

[lxc]
test002 ansible_host=192.168.5.231
test003 ansible_host=192.168.5.229

[servers:children]
lxc
pvevm
pvevmdeb
