---
- name: "podman testing"
  hosts: podman-testing
  remote_user: ansi
  vars:
    ansible_private_role_vars: true

  roles: 
    - role: base/deb-base
    - role: sec/firewalld
    - role: podman/podman
#    - role: podman/podman_infra
    - role: podman/podman_storage
    - role: podman/podman_main


