---
- name: "Provisioning containers on Proxmox as defined in the Ansible inventory file" 
  hosts: proxmoxlxc
  gather_facts: false

  tasks:
    - name: "Retrieving ssh public key from local system"
      become: no
      delegate_to: 127.0.0.1
      ansible.builtin.slurp:
        src: "~/.ssh/id_ed25519.pub"
      register: ssh_pub_key

    - name: "Provisioning LXC containers on Proxmox node {{ proxmox_host }}"
      delegate_to: 127.0.0.1
      community.proxmox.proxmox:
        api_user: "{{ proxmox_api_user }}@pam"
        api_password: "{{ proxmox_api_passwd }}"
        api_host: "{{ proxmox_host }}"
        vmid: "{{ vmid }}"
        memory: "{{ memory }}"
        cpus: "{{ cpus }}"
        netif: '{"net0":"name={{ proxmox_netif }},ip={{ ansible_host }}/{{ subnet_mask }},gw={{ gateway }},bridge={{ proxmox_netbridge }}"}'
        #password: "{{ proxmox_lxc_default_pass }}"
        hostname: "{{ inventory_hostname }}"
        storage: "{{ proxmox_vm_storage }}"
        node: "{{ proxmox_node }}"
        #mount_volumes: "{{ bind_mounts }}"
        ostemplate: "{{ proxmox_template_storage }}/{{ ostemplate }}"
        timeout: 300
        pubkey: "{{ ssh_pub_key['content'] | b64decode }}"
        onboot: true
        state: present

    - name: "Waiting for container creation"
      ansible.builtin.wait_for:
        timeout: 5
      delegate_to: localhost

    - name: "Adding bind mounts to Proxmox containers"
      delegate_to: 127.0.0.1
      community.proxmox.proxmox:
        api_user: "{{ proxmox_api_user }}@pam"
        api_password: "{{ proxmox_api_passwd }}"
        api_host: "{{ proxmox_host }}"
        vmid: "{{ vmid }}"
        hostname: "{{ inventory_hostname }}"
        mount_volumes: "{{ bind_mounts }}"
      when: "bind_mounts is defined and bind_mounts | length > 0"

    - name: "Starting LXC containers on Proxmox node {{ proxmox_host }}"      
      delegate_to: 127.0.0.1
      community.proxmox.proxmox:
        node: "{{ proxmox_host }}"
        vmid: "{{ vmid }}"
        api_user: "{{ proxmox_api_user }}@pam"
        api_password: "{{ proxmox_api_pass }}"
        api_host: "{{ proxmox_host }}"
        state: started

    - name: "Installing git and ansible"
      become: true
      ansible.builtin.package:
        name:
          - git
          - ansible
        state: latest

- name: "Running first plays to set up ansible-pull"
  hosts: deblxctest
  become: true

  tasks:
    - name: "Installing git and ansible"
      ansible.builtin.package:
        name:
          - git
          - ansible
        state: latest
