---
######## PODMAN INFRASTRUCTURE #########################################
# Creates base infrastructure before adding "production" containers
# - Creates an internal podman network for containers
# - Creates reverse proxy (caddy) and DNS (coredns) containers 
# - Ensures container storage is initialized
# - Copies and schedules offsite backup script
# ######################################################################



#####################################################
# Creating podman default internal network

- name: debug_varname
  ansible.builtin.debug:
    msg: "{{ pm_default_internal_network }}"

- name: "Creating default podman internal network"
  ansible.builtin.include_role:
    name: podman/podman_network
  vars:
    current_network: "{{ pm_default_internal_network }}"

#####################################################
# Creating DNS and proxy containers

- name: "Creating DNS and proxy files | creating parent directories"
  become: true
  become_user: "{{ pm_host_username }}"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ pm_host_username }}"
    group: "{{ pm_host_username }}"
    mode: '0755'
  loop:
    - "{{ pm_dnsfile | dirname }}"
    - "{{ pm_proxyfile | dirname }}"

- name: "Creating DNS and proxy files | checking for existing proxy file"
  become: true
  become_user: "{{ pm_host_username }}"
  ansible.builtin.stat:
    path: "{{ pm_proxyfile }}"
  register: check_proxyfile
 
- name: "Creating DNS and proxy files | creating proxy file if it doesn't exist"
  become: true
  become_user: "{{ pm_host_username }}"
  ansible.builtin.file:
    path: "{{ pm_proxyfile }}"
    state: touch
    owner: "{{ pm_host_username }}"
    group: "{{ pm_host_username }}"
    mode: '0640'
  when: not check_proxyfile.stat.exists

- name: "Creating DNS and proxy files | adding header to DNS file"
  become: true
  become_user: "{{ pm_host_username }}"
  ansible.builtin.blockinfile:
    path: "{{ pm_dnsfile }}"
    create: true
    insertbefore: "BOF"
    owner: "{{ pm_host_username }}"
    group: "{{ pm_host_username }}"
    mode: '0640'
    block: |
      $ORIGIN {{ domain }}.
      $TTL 300

      @       IN SOA  {{ pm_nameserver_hostname }}.{{ domain }}. admin.{{ domain }}. (
                  2026050301 3600 600 86400 300
      )

      @       IN NS   {{ pm_nameserver_hostname }}.{{ domain }}.

      {{ pm_nameserver_hostname }}   IN    A   {{ ansible_facts['default_ipv4']['address'] }} 


## NOTE: 
#   vars:
#     ansible_private_role_vars: true
# MUST be set in the playbook this role is run in, otherwise the quadlet module won't work!!!!!
#
- name: "Installing CoreDNS and Caddy quadlets"
  ansible.builtin.include_role:
    name: podman/quadlet
  loop: 
    - caddy
    - coredns
  loop_control:
    loop_var: infra_nm
  vars:
    current_container: "{{ infra_nm }}"

#####################################################




