---
restic_user: "restic"
script_repo_url: "https://codeberg.org/ouphaloc/ResticBackup"
script_repo_dest: "/opt/resticBackup"
script_path: "/opt/resticBackup/restic-b2-backup.sh"
env_file_path: "/root/.restic.env"

restic_cache: "/var/cache/restic"
restic_keep_daily: "3"
restic_keep_weekly: "1"
restic_keep_monthly: "2"
restic_keep_yearly: "3"
restic_backup_schedule: "*-*-* 4:30:00"

check_subset_g: "5"

