---
- name: "Copying podman quadlets from defined podman_containers list"
  ansible.builtin.include_role:
    role: podman/quadlet
  loop: "{{ podman_containers }}"
  loop_control:
    loop_var: container_nm
  vars:
    current_container: "{{ container_nm }}"

