---
- name: "Installing mpd related packages on Arch-based distributions"
  become: true
  community.general.pacman:
    name:
      - mpd
      - mpc
      - ncmpcpp
      - beets
    state: present
  when: ansible_distribution == "Archlinux"

- name: "Setting up mpd in a per-user configuration"
  ansible.builtin.include_tasks:
    file: per-user.yml
  when: mode == "user"

- name: "Configuring ncmpcpp"
  ansible.builtin.include_tasks:
    file: ncmpcpp.yml
  when: target_user is defined
