---
#- name: "Remove existing quadlet files"
#  become: true
#  ansible.builtin.file:
#    dest: "{{ pm_rootless_ctdir }}/it-tools.container"
#    state: absent

#- name: "Copy quadlet files into quadlet directory"
#  become: true
#  ansible.builtin.copy:
#    src: ittools.container
#    dest: "{{ pm_rootless_ctr_dir }}/it-tools.container"
#  notify: reload-systemd
# Get the UID of xadmin for systemd user scope
#
- name: "Load container vars file"
  ansible.builtin.include_vars:
    dir: "{{ playbook_dir }}/podman_vars/{{ current_container }}"
    files_matching: 'main.yml'
  when: current_container is defined

- name: "debug"
  ansible.builtin.debug:
    msg: "Now installing {{ current_container }}"

- name: "Assembling facts"
  ansible.builtin.set_fact:
    container_image_full: "{{ container_image }}:{{ container_version_tag }}"
    quadlet_filename: "{{ container_name }}.container"

- name: "Ensuring volume mounts are present on host"
  become: true
  ansible.builtin.file:
    path: "{{ item.ext }}"
    mode: '0755'
    owner: "{{ pm_host_username }}"
    group: "{{ item.group | default (pm_host_username) }}"
    state: directory
  loop: "{{ volumes }}"
  when: volumes | length > 0

- name: "Creating directories for extra_files, if necessary"
  become: true
  ansible.builtin.file:
    path: "{{ item.dest | dirname }}"
    mode: '0755'
    owner: "{{ pm_host_username }}"
    group: "{{ item.group | default (pm_host_username) }}"
    state: directory
  loop: "{{ extra_files }}"
  when: extra_files | length > 0

- name: "Copying extra files"
  become: true
  ansible.builtin.template:
    src: "{{ playbook_dir }}/podman_vars/{{ current_container }}/extra_files/{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ pm_host_username }}"
    group: "{{ item.group | default (pm_host_username) }}"
    mode: '0644'
  loop: "{{ extra_files }}"
  when: extra_files | length > 0

- name: "Copying {{ container_name }} quadlet file template into remote quadlet directory"
  become: true
  #become_user: "{{ pm_host_username }}"
  ansible.builtin.template:
    src: "quadlet.container.j2"
    dest: "{{ pm_rootless_ctdir }}/{{ quadlet_filename }}"
    owner: "{{ pm_host_username }}" 
    group: "{{ pm_host_username }}"
    mode: '0640'
  register: qdcpy

- name: "Checking for errors in {{ container_name }} quadlet file"
  ansible.builtin.command:
    argv:
      - /usr/lib/systemd/system-generators/podman-system-generator 
      - --user
      - --dryrun

# /usr/lib/systemd/system-generators/podman-system-generator --user --dryrun
#
#- name: "Daemon-reload"
#  become: true become_user: "{{ pm_host_username }}"
#  ansible.builtin.systemd_service:
#    scope: user
#    daemon_reload: true
#  environment:
#    XDG_RUNTIME_DIR: "{{ user_runtime_dir }}"

- name: "Starting systemd user"
  become: true
  become_user: "{{ pm_host_username }}"
  ansible.builtin.systemd_service:
    name: "{{ container_name }}.service"
    state: restarted
    scope: user
    enabled: true
    daemon_reload: true
  when: qdcpy.changed

- name: "Forwarding low-numbered ports with firewalld"
  become: true
  ansible.posix.firewalld:
    zone: public
    port_forward:
      - port: "{{ item.forward }}"
        proto: "{{ item.proto }}"
        toport: "{{ item.ext }}"
    permanent: true
    state: enabled
  when: item.forward is defined
  loop:  "{{ publish_ports }}"
  notify:
    - reload-firewalld

- name: "Allow port on firewalld"
  become: true
  ansible.posix.firewalld:
    zone: public
    port: "{{ item.ext }}/{{ item.proto }}"
    permanent: true
    state: enabled
  when: item.forward is not defined
  loop: "{{ publish_ports }}"
  notify: 
    - reload-firewalld

- name: "Clearing variables"
  set_fact:
    extra_files: []
    volumes: []
    publish_ports: []
    exec: []
