---
#- name: "Remove existing quadlet files"
#  become: true
#  ansible.builtin.file:
#    dest: "{{ pm_rootless_ctdir }}/it-tools.container"
#    state: absent

#- name: "Copy quadlet files into quadlet directory"
#  become: true
#  ansible.builtin.copy:
#    src: ittools.container
#    dest: "{{ pm_rootless_ctr_dir }}/it-tools.container"
#  notify: reload-systemd
# Get the UID of xadmin for systemd user scope
#
- name: "Load container vars file"
  ansible.builtin.include_vars:
    dir: "{{ playbook_dir }}/podman_vars/{{ current_container }}"
  when: current_container is defined

- name: debug
  ansible.builtin.debug:
    var: current_container

- name: "Assembling facts"
  ansible.builtin.set_fact:
    container_image_full: "{{ container_image }}:{{ container_version_tag }}"
    quadlet_filename: "{{ container_name }}.container"

- name: debug
  ansible.builtin.debug:
    msg: "{{ container_image_full }} to {{ quadlet_filename }}"

- name: "Get UID of {{ pm_host_username }} for systemd user scope"
  become: false
  ansible.builtin.getent:
    database: passwd
    key: "{{ pm_host_username }}"
  register: user_info

- name: debug
  ansible.builtin.debug:
    var: user_info

# Wait for user runtime directory
- name: Wait for user runtime directory
  become: false
  ansible.builtin.wait_for:
    path: "/run/user/{{ user_info.ansible_facts.getent_passwd.pm[2] }}"
    state: present
    timeout: 60

# Set runtime directory fact
- name: Set user runtime directory fact
  become: false
  ansible.builtin.set_fact:
    user_runtime_dir: "/run/user/{{ user_info.ansible_facts.getent_passwd.pm[2] }}"

- name: debug
  ansible.builtin.debug:
    msg: "Runtime dir: {{ user_runtime_dir }}"

- name: "Copying {{ container_name }} quadlet file template into remote quadlet directory"
  become: true
  #become_user: "{{ pm_host_username }}"
  ansible.builtin.template:
    src: "quadlet.container.j2"
    dest: "{{ pm_rootless_ctdir }}/{{ quadlet_filename }}"
    owner: "{{ pm_host_username }}" 
    group: "{{ pm_host_username }}"
    mode: '0640'

# /usr/lib/systemd/system-generators/podman-system-generator --user --dryrun


#- name: "Daemon-reload"
#  become: true
#  become_user: "{{ pm_host_username }}"
#  ansible.builtin.systemd_service:
#    scope: user
#    daemon_reload: true
#  environment:
#    XDG_RUNTIME_DIR: "{{ user_runtime_dir }}"

- name: "Starting systemd user"
  become: true
  become_user: "{{ pm_host_username }}"
  ansible.builtin.systemd_service:
    name: "{{ container_name }}.service"
    state: started
    scope: user
    daemon_reload: true

#- name: "Allow port on firewalld"
#  become: true
#  ansible.posix.firewalld:
#    zone: public
#    port: "{{ item.ext }}/{{ item.proto }}"
#    permanent: true
#    state: enabled
#  loop: "{{ publish_ports }}"
#  notify: 
#    - reload-firewalld
